name: virtual_scroll
description: virtual-scroll component for AngularDart
version: 0.1.1
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0

dev_dependencies:
  browser:
  dart_to_js_script_rewriter:

transformers:
- angular:
    entry_points: example/main.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc